### ISSUE TITLE
Inventory Server

### ISSUE THREAD

**Issue by olendorf** [olendorf/slapp_data_2#71]
- Update contents to database 

- Accepts request to give items

- Gives items to users in response to requests from the server. 

- [x] API - depends on #76

- [x] Policy - depends on #125

- [x] Inventory - depends on #75 

- [ ] Inworld object 

- [ ] Request handler for inworld object 

- [ ] Admin Interface - depends on #118

- [ ] User Interface -depends on #119

**Comment by olendorf** [comment]
Inventory done enough to check off.
